-
    image_name: demo
    objects:
        -
          class_id: 1
          xmin: 1
          xmax: 1
          ymin: 1
          ymax: 1
        -
          class_id: 1
          xmin: 1
          xmax: 1
          ymin: 1
          ymax: 1
